### ISSUE TITLE
auto date dd.mm.yy

### ISSUE THREAD

**Issue by azzeli0** [hkgnp/logseq-datenlp-plugin#23] opened 2022-10-03 19:32 UTC
strange behaviour to detect date in this format dd.mm.yy

<img width="252" alt="Screenshot 2022-10-03 at 21 25 33" src="https://user-images.githubusercontent.com/114951926/193661775-60391c94-bc8e-478b-b367-090b3bc044de.png">

**Comment by hkgnp** [comment] 2022-10-09 03:52
Sorry, I am not sure what your error is.

**Comment by cleanclothes-pi** [comment] 2022-10-16 03:36
Hi @hkgnp , think I suspect that I run into the same problem. The issue is that datenlp plugin does not respect the "preferred date format" in the Editor setting menu.

My preferred date format of my two graphs are set to: `do MMM yyyy` and `E, dd.MM.yyyy`
Regardless datenlp-plugin always parsed an output in format for both of them: `[[MMM do, yyyy]]`

<img width="825" alt="Screen Shot 2022-10-15 at 23 32 11" src="https://user-images.githubusercontent.com/58788103/196016647-21e55eec-0e8a-4b62-a0c7-6b2df68b9891.png">

**Comment by hkgnp** [comment] 2022-11-05 15:38
This should be fixed in the latest version. Do update and let me know if the issue still persists.

Do note that in Logseq, E and EEE seem to look the same in the journal pages. However, if you use the plugin with E, it would show E, and if you use EEE, it will show EEE. Hence, suggest to use EEE instead of E so that there will be no conflicts.

**Comment by cleanclothes-pi** [comment] 2022-11-06 03:04
I tested and it parsed the dates as expected, and changed same as the EEE date format as suggested—also works great. Thank you so much for your work!

**Closed** 2022-11-06 04:07 UTC
